[build]
publish = "dist"
command = "yarn build"

[[redirects]]
from = "https://k.rohmer.rocks/*"
to = "https://karolinrohmer.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://karo.rohmer.rocks/*"
to = "https://karolinrohmer.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://karolin.rohmer.rocks/*"
to = "https://karolinrohmer.com/:splat"
status = 301
force = true
